### ISSUE TITLE
Documentation and examples

### ISSUE THREAD

**Issue by tauren** [chrisguttandin/rxjs-broker#45]
I'm looking into using RxJS with WebRTC peer connections and data channels, and this project shows up at the top of a google search. After reviewing the code and tests, I'm still not quite sure what this project does or if it would be useful to use.

Are there blog postings, slide decks, example code, or any other resources where I could learn more about the problem rxjs-broker is solving and how to use it? 

I know there's a lot more boilerplate required to use WebRTC than WebSockets, but I'd like to abstract much of the complexity away into something like this:
http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-webSocket

**Comment by chrisguttandin** [comment]
Hi @tauren, many thanks for having a look at this package. Adding a little explanation on how to use
it was on my todo list for a long time. Unfortunately I never got around to actually do it.

My intent with this package was to provide simple tools to multiplex communications over a WebSocket or a single WebRTC DataChannel. I ended up with two methods `connect()` and `wrap()`. The former takes an URL and the latter expects to receive a WebRTC DataChannel. Both return an enhanced subject. These subjects have an additional `mask()` method which masks all incoming and outgoing data with the given JSON structure.

I know that this all sounds very complicated, but the usage is in fact very intuitive. I updated the README file and added an example on how to use it. Please let me know if that answers your question.

**Comment by tauren** [comment]
The README helps a lot, thanks! Nice work, the project looks interesting and well designed. I may be able to utilize `wrap()`, but I don't think `mask()` will work for me. 

Some of the data coming over my DataChannels is JSON that has been serialized into a binary stream which can span multiple channel messages. Multiple messages are then assembled and deserialized into JSON data. At that point, the `mask` feature might prove useful, but there would need to be some additional serialization/deserialization logic that would need to go in there somehow.

Is it correct to say that `rxjs-broker` doesn't do anything to help with managing the RtcPeerConnection, such as creating offers, icecandidates, and helping manage the various lifecycle states? I stumbled upon this project while looking for some library that would help manage the various peer states and error conditions, automatically reconnecting as needed.

**Comment by chrisguttandin** [comment]
Yes, you’re absolutely right. This package doesn’t handle the signaling process. I do use another package for that, but it is even more specific. It does for example require the server to send messages with a specific format. I haven’t open sourced it because I thought it might not be useful for anyone else. In fact that’s the reason why the wrap method of `rxjs-broker` requires an already established DataChannel.

**Comment by chrisguttandin** [comment]
Hi @tauren, I'm closing this issue now. Please feel free to open another one if you encounter further problems.
